server {
    listen          80 default_server; # Falls back here if doesn't match other server names. Even if default_server wasn't set, would fall back here since it's the first server block.
    server_name     _;
    location / {
        proxy_pass http://host.docker.internal:7000/; # instance 000
    }
}

server {
    listen          80;
    server_name     example.com; # Emulating with host header
    location / {
        proxy_pass http://host.docker.internal:7001/; # instance 001
    }
}

server {
    listen          80;
    server_name     local.testing.com; # Emulating with host header
    location / {
        proxy_pass http://host.docker.internal:7002/; # instance 002
    }
}
