server {
    listen 80;
    
    location / {
        proxy_pass http://host.docker.internal:7000/;
    }

    location /instance-001/ {
        proxy_pass http://host.docker.internal:7001/;
    }

    location /instance-002/ {
        proxy_pass http://host.docker.internal:7002/;
    }
}
